### ISSUE TITLE
Using built-in Gorm migration instead of sql-migrate

### ISSUE THREAD

**Issue by mehdihadeli** [WesionaryTEAM/go_clean_architecture#79]
Hi,
Why do you use `sql-migrate` instead of built-in Gorm migration?

**Comment by dipeshdulal** [comment]
The decision was made before Gorm v2 which didn't have feature to delete columns at that time. During that I time we searched for different solutions and stuck with `sql-migrate`. The Gorm library have now added the feature but since we have stuck with it and team has worked great with the library we haven't thought of changing it. 

The flexibility provided by `sql-migration` library is enabling us to write migrations in sql, selected rollback of migration files etc. which are some added benefits. 

if you want to use different migration system altogether we might need to add some plugin mechanisms in the framework. 🤔

**Comment by mehdihadeli** [comment]
@dipeshdulal make senses :) that was just a question in my mind.  I didn't work with `sql-migrate` but I ithinks it is very similar to [golang-migrate/migrate](https://github.com/golang-migrate/migrate), and it is really nice tools for none  Gorme apps.
